### ISSUE TITLE
Centos6 x32 not  working  Please help

### ISSUE THREAD

**Issue by gudge25** [sipcapture/captagent#158]
Captagent  + libuv- was compiled  from src 

[root@goip16 captagent]# cat /etc/redhat-release
CentOS release 6.6 (Final)

[root@goip16 captagent]# uname -a
Linux goip16 2.6.32-358.6.1.el6.i686 #1 SMP Tue Apr 23 18:13:20 UTC 2013 i686 i686 i386 GNU/Linux

[root@goip16 captagent]# /usr/local/captagent/sbin/captagent -n -f  /usr/local/captagent/etc/captagent/captagent.xml

[NOTICE] Loaded core config
[ERR] modules.c:75 dlopen error [/usr/local/captagent/lib/captagent/modules/transport_hep.so: undefined symbol: uv_key_create]
[ERR] conf_function.c:458 find_export_record: <send_hep> not found

parse error (16,30-31): unknown command, missing loadmodule?

ERROR: bad config file (1 errors)
IS RTCP

[ERR] protocol_sip.c:132 Couldnot find this call

IS RTCP

[ERR] protocol_sip.c:132 Couldnot find this call

IS RTCP

[ERR] protocol_sip.c:132 Couldnot find this call

IS RTCP

**Comment by lmangani** [comment]
Hi @gudge25 
```
undefined symbol: uv_key_create
```

As you can see from the error ```libuv``` is required for the latest Captagent to work - I'm not sure if this is easily provided on older CentOS (surely not officially) so you might want to give [HEPlify](https://github.com/sipcapture/heplify) a try instead of Captagent as it has next to no requirements.
