### ISSUE TITLE
no rtcp sent by captagent

### ISSUE THREAD

**Issue by agicblack** [sipcapture/captagent#161]
profile name="socketspcap_rtcp" description="RTCP Socket" enable="true" serial="2014010402"

but don't work/

Couldnot find this call

**Comment by lmangani** [comment]
@agicblack "Could not find this call" actually means its working, but cannot find a correlation between the captured IP:PORT RTCP stream and a known SIP/SDP Session - this invalidates the correlation, most likely due to NAT or similar in the SDP. Hard to tell without the actual knowledge of the network.

Hope this helps
