### ISSUE TITLE
[ERR] conf_function.c:458 find_export_record: <parse_tls> not found

### ISSUE THREAD

**Issue by billsimon** [sipcapture/captagent#167]
Built latest captagent with TLS and followed the wiki to configure it.

Using the default tcp_capture_plan.cfg I get this error in syslog upon startup.

**Comment by lmangani** [comment]
@billsimon whats the error? I'll take a guess with a known bug, and suggest to load the ```tcp_procotocol``` before the ```pcap_socket```

**Comment by billsimon** [comment]
Error in subject line of ticket. I'll try your suggestion.

**Comment by adubovikov** [comment]
the module protocol_tcp has not been loaded

On Feb 9, 2018 18:26, "billsimon" <notifications@github.com> wrote:

Error in subject line of ticket. I'll try your suggestion.


On February 9, 2018 12:25:25 PM Lorenzo Mangani <notifications@github.com>
wrote:


> @billsimon whats the error? I'll take a guess with a known bug, and
suggest
> to load the ```tcp_procotocol``` before the ```pcap_socket```
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/sipcapture/captagent/issues/167#issuecomment-364500552

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sipcapture/captagent/issues/167#issuecomment-364500967>,
or mute the thread

**Comment by billsimon** [comment]
@lmangani was correct; I needed to load protocol_tcp before pcap_socket
