### ISSUE TITLE
Feedback/Suggestion Custom Parameter - Text rather than Int

### ISSUE THREAD

**Issue by Si-Richards** [sipcapture/captagent#210]
Using Captagent over multiple servers all clustered together.

The current paramater capture-id is an int and requires correlation if you have say 20+ servers.
It would be fantastic if it would allow a text or the FQDN of the host.

<param name="capture-id" value="FOO@BAR.COM"/>

**Comment by adubovikov** [comment]
unfortunately ID can be only UINT32 value, as it has been planned by design, but teoreticaly we can push or 0x0013 = group ID or 0x0026 "Tags" for and additional information about "capture node"

currently the captagent/heplify doesnt' send these values, but it can be extended.

https://github.com/sipcapture/HEP/blob/master/docs/HEP3%20Network%20Protocol%20Specification%20_REV%2028.pdf

**Comment by negbie** [comment]
@Si-Richards https://github.com/sipcapture/heplify/pull/102/commits/dd34d2b018d7baf244b3178e429b09fbb0837215
