### ISSUE TITLE
Installing captagent on Debian 10 - configure: error: captagent requires but cannot find libfl

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/captagent#229]
Hello,

i tried to install captagent 6.3.1 on a debian 10 server and got this error:

```
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
configure: error: captagent requires but cannot find libfl
```

i tried it like descripted here for Debian 9 installation (but i need it on Debian 10):
https://github.com/sipcapture/captagent/wiki/Installation

I also searched for solutions on google, but can't find something helpful stuff :/

**Comment by kYroL01** [comment]
Hello @ciscospirit . At the moment captagent is availlable for Debian 9 and Centos 7.
I need to create a new installer for Debian 10 because I think there are several differences from 9. I'll take a look asap and let you know.
Anyway feel free to send us a PR if you find a solution before.
NOTE: I'll release a new captagent version in the next month with some updates.

Thanks for reporting it

**Comment by adubovikov** [comment]
@ciscospirit please install flex-devel

**Comment by ciscospirit** [comment]
> @ciscospirit please install libfl2 libfl-dev

root@spce:~# apt-get install flex-devel
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package flex-devel

not possible on Debian 10.

**Comment by ciscospirit** [comment]
i have sipcapture running on a machine where i have installed Debian 9 and upgrade later to debian 10 and it is working.
so sipcapture is working with debian 10 just installing is not working on vanilla debian 10.

**Comment by ciscospirit** [comment]
> libfl2 libfl-dev

yes its working now :)

**Comment by adubovikov** [comment]
super. You know that to do here: https://github.com/sipcapture/homer/stargazers :-)
