### ISSUE TITLE
Matching of profile names wrong in get_profile_index_by_name

### ISSUE THREAD

**Issue by boettner** [sipcapture/captagent#230]
This does not work for two profiles like `homer` and `homer_new`. The second profile must not begin with the name of the first profile. This is confusing.

https://github.com/sipcapture/captagent/blob/7075678334d3ddd766dd14485f7da10fd62abd60/src/modules/transport/hep/transport_hep.c#L201

**Comment by adubovikov** [comment]
yes, you are right. Let me revert it

**Comment by adubovikov** [comment]
done. https://github.com/sipcapture/captagent/commit/95dc88c4032592e2b6aa05b1946058d1031f96b4

can you please check ?

**Comment by AndreasTarp** [comment]
Hi, 

typo in line 212 (NUL instead of NULL) ;-)
https://github.com/sipcapture/captagent/blob/95dc88c4032592e2b6aa05b1946058d1031f96b4/src/modules/transport/hep/transport_hep.c#L212

Does your change really fix the issue, or would it now occur in case of switched profile names, e.g. first profile is named homer_old and second one homer and reference from captureplan is pointing to "homer"? 

So maybe check first which string has bigger size and than use that string to compare to shorter string to ensure not matching only parts.

Best regards from Düsseldorf, Andreas

**Comment by adubovikov** [comment]
you are right, let me change it

**Comment by adubovikov** [comment]
Done. Thanks for the tip :-) Einen schönen Tag!

**Comment by adubovikov** [comment]
If i undertstood correct - we can close the ticket. Please reopen it on demand
